config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }
  root to: 'home#index'
  resources :categories
  resources :roles
  resources :posts
  resources :comments
  resources :admins
  resources :ratings

  get '/post/:id', to: 'home#post', as: 'home_post'
  post '/create/admin', to: 'admins#create', as: 'admin_create'
end

app/views/admins/_form.html.erb
<div class="bg-light">
    <%= form_with model: @admin do |form| %>
        <div class="input-group input-group-outline mb-5 w-80 mx-3 pt-5 mx-5">
            <%= form.text_field :email, class: "form-control", placeholder: 'Email', :required => true%>
        </div>

        <div class="input-group input-group-outline mb-5 mx-3 w-80 mx-5">
            <%= form.password_field :password, maxlength: 15, placeholder: 'Senha',disabled: true, class: "form-control p-3 mb-2" %>
        </div>

        <div class="input-group input-group-outline mb-5 mx-3 w-80 mx-5">
            <%= form.password_field :password_confirmation, placeholder: 'Confirmar senha', disabled: true, class: "form-control p-3 mb-2" %>  
        </div>

        <div class="bg-light mb-3 mx-5">
            <input type="checkbox" id="pass" name="pass">
            <label for="pass">alterar senha?</label>
        </div>
        <div class="input-group input-group-outline mb-3 form-control mx-5">
            <%= form.select :role_id, options_for_select([
            ['Admin', 1], 
            ['Comentarista', 2], 
            ['Leitor', 3]], @admin.role_id) %>
        </div>
        <div class="container">
            <%= form.submit 'Salvar', class: "btn btn-lg text-white bg-gradient-dark font-weight-bold mb-5" %>
            <%= link_to 'Voltar', admins_path, class: "btn btn-lg text-white bg-gradient-dark font-weight-bold mb-5" %>
        </div>
    <% end %>
</div>

app/views/admins/edit.html.erb
<div>
    <div class="container">
        <div class="card-header bg-gradient-dark">
            <h4 class="font-weight-bolder"></h4>
            <p class="mb-0 fonts-L text-white">Editando email --<%= @admin.email %> </p>
        </div>
        <%= render partial: 'form' %>
    </div>
</div>
<script>
    $( "#pass" ).click(function() {
        if ($('#pass').is(":checked") == true) {
            $('#admin_password').attr("disabled", false);
            $('#admin_password_confirmation').attr("disabled", false);
        }
        else { 
            $('#admin_password').attr("disabled", 'disabled');
            $('#admin_password_confirmation').attr("disabled", 'disabled');
        }
    })
</script>

app/views/admins/index.html.erb
<div class="container py-4">
    <div class="row">
        <div class="col-12">
            <div class="card my-4 px-5 border-5">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class=" shadow-dark border-radius-lg pt-4 pb-3 border border-dark border-2">
                    <div class="container">
                    <h2 class="ps-3 text-black">Usuarios</h2>
                    <%= link_to new_admin_path, class: "btn btn-outline-dark" do %>
                        novo
                        <i class="fas fa-plus "></i>
                    <% end %>
                    </div>
                    </div>
                </div>
                <div class="card-body px-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <tbody>
                        <% @admin.each do |admin| %>
                            <tr class="container text-black">
                                <td>
                                    <%= admin.email %>
                                </td>
                                <td>
                                    <%= admin.role.username %>
                                </td>
                                <td class="align-middle">
                                <%= link_to 'Editar', edit_admin_path(id: admin.id), class: "btn btn-sm text-secondary font-weight-bold" %>
                                <%= link_to 'Deletar', admin_path(id: admin.id), method: :delete, data: { confirm: "Tem certeza?" }, class: "btn btn-sm text-white bg-gradient-dark font-weight-bold" %>
                                </td>
                            </tr>
                            <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admins/new.html.erb
    <div class="container">
        <div class="card-header">
            <h2 class="fonts-L">User</h4>
            <p class="mb-0 fonts-L">Novo User</p>
        </div>
        <div class=" bg-light">
    <%= form_with model: @admin do |form| %>
        <div class="input-group input-group-outline mb-5 w-80 mx-3 pt-5">
            <%= form.text_field :email, class: "form-control", placeholder: 'Email', :required => true%>
        </div>

        <div class="input-group input-group-outline mb-5 mx-3 w-80 ">
            <%= form.password_field :password, maxlength: 15, placeholder: 'Senha', class: "form-control p-3 mb-2" %>
        </div>

        <div class="input-group input-group-outline mb-5 mx-3 w-80 ">
            <%= form.password_field :password_confirmation, placeholder: 'Confirmar senha',  class: "form-control p-3 mb-2" %>  
        </div>
        <div class="input-group input-group-outline mb-3 mx-4">
            <%= form.select :role_id, options_for_select([
            ['Admin', 1], 
            ['Comentarista', 2], 
            ['Leitor', 3]], @admin.role_id)%>
        </div>
        <div class="container">
            <%= form.submit 'Salvar', class: "text-white btn btn btn-outline-dark bg-gradient-dark font-weight-bold text-xs m-2 mb-5 mt-5" %>
            <%= link_to 'Voltar', admins_path, class: "text-white btn btn btn-outline-dark bg-gradient-dark font-weight-bold text-xs m-2 mb-5 mt-5" %>
        </div>
    <% end %>
    </div>
</div>