config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }
  root to: 'home#index'
  resources :categories
  resources :roles
  resources :posts
  resources :comments
  resources :admins
  resources :ratings

  get '/post/:id', to: 'home#post', as: 'home_post'
  post '/create/admin', to: 'admins#create', as: 'admin_create'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index
        @posts = Post.order(:created_at)
        @categories = Category.order(:name)
    end

    def post
        @post = Post.find(params[:id])
        @comment = Comment.new
        @comment_son = Comment.new
        @comments = Comment.where(post_id: @post.id).where(comment_id: nil).order(created_at: :desc)
        @ratings = Rating.new
        @average = Rating.where(post_id: @post.id).average("rate")
    end
end

app/views/home/_comments.html.erb
<% comments.each do |comment| %>
<div class="container"> <%# Comentario pai %>
    <table class=" mt-2 table-responsive text-white bg-gradient-dark d-flex m-2 ps-0 border-radius-lg">
        <tr>
            <td>
                <p class="font-weight-bold  p-2 d-none d-md-block"><%= comment.admin.email %></p>
                <hr class="text-light d-none d-md-block" >
            </td>
            <hr class="text-light " style="width:50%;text-align:left;margin-left:0">
        </tr>
            <td>
                <p class="font-weight-bold mb-0 p-2 mb-2 "><%= comment.content %></p>
            </td>
    </table>
            <td>
                <p class="font-weight-bold mb-0 px-2"><%= comment.created_at.strftime("%H:%M") %></p>
            </td>
</div>
<div class="container"> <%# comentario filho %>
    <table class="mt-3 table-responsive d-flex ps-0 mb-2 border-radius-lg">
        <tbody id="comment-list">
            <% comment.comments.each do |son|%>
                <tr>
                    <td>
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#000" class="bi bi-person-fill " viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    </svg>
                        <%= son.admin.email %>
                    </td>
                    <td>
                        <p class="m-2 px-5"><%= son.content %></p>
                    </td>
                    <td>
                        <p class="font-weight-bold mb-0 px-2"><%= comment.created_at.strftime("%H:%M") %></p>
                    </td>
                </tr>   
            <% end %>
            <hr>
        </tbody>
    </table>
    <% if current_admin %> <%# area pra comentar do comentario filho%>
        <div>
            <%= form_with model: @comment_son, local: false, :html => {:id =>'' } do |form| %>
                <div class="bg-gradient-light border-radius-lg fonts-L">
                    <div class="text-dark font-weight-bolder opacity-7 form-control">
                        <%= form.text_area :content, maxlength: 255, class: "bg-light form-control p-2", placeholder: "Escreva seu Comentario...", required: true%>
                        <%= form.hidden_field :post_id, :value => comment.post_id %>
                        <%= form.hidden_field :comment_id, :value => comment.id %>
                    </div>
                    <div>
                        <%= form.submit 'Responder', class: "text-white btn btn btn-outline-dark bg-gradient-dark font-weight-bold text-xs m-2 cursor" %>
                    </div>
                </div>
            <% end %>
        </div>
        <hr>
    <% end %>
</div>
<% end %>

app/views/home/_rate.html.erb
<div class="container">
    <h3 class="text-dark my-3 fonts-L">AVALIAÇÃO
        <i class="fas fa-star fa-1x mt-3" style="color: #FFFF00;"></i>
    </h3>
    <%= form_with model: @ratings, local: false do |f| %>
        <% (1..5).each do |rating| %>
        <%= f.label :rate, for:"rating_rate_#{rating.to_i}" do %>
            <i id="<%= rating%>" class="fas fa-star fa-2x mt-3"></i>
        <% end %>
        <%= f.radio_button "rate", rating.to_i, style:'display:none;'%>
        <% end %>
        <%= f.hidden_field :post_id, value: @post.id %>
        
        <span id="rating-post">
            <%= number_with_precision(@average, precision: 1) %>
        </span>
        <%= f.submit ('Avaliar'), class: "btn btn-lg text-dark btn btn btn-outline-dark fonts-L mt-2 mb-0 m-4"%> 
    <% end %>
</div>

app/views/home/index.erb
<div class="container-fluid ">
  <div class="container mt-2">
  <main role="main" class="text-lg">
    <div>
      <h1 class="jumbotron-heading neon mb-5">BLOG</h1>
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <% @posts.each do |post| %>
              <div class="col-lg-4 col-md-6 mt-4 mb-4">
                <div class="card z-index-2 bg-gradient-light">
                  <!-- POST IMG -->
                    <div class="card-header shadow-dark border-radius-lg pe-1 page-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
                          <%= image_tag post.image.variant(resize_to_fill: [381, 218]), class:"img-fluid"%>
                    </div>
                  <!-- POST TXT -->
                    <div class="card-body text-dark container-fluid py-1 px-3"style="height:250px;">
                      <h6 class="card-text text-dark"><%= post.name %></h6>
                      <p class="card-text"><%= post.summary %>.</p>
                      <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted fixd-bottom"><%= post.created_at.strftime("%H:%M")%></small>
                        <div class="card-footer" :last-child>
                          <%= link_to "Ver", home_post_path(id: post.id), :class => 'btn btn-sm text-dark btn-outline-secondary' %>
                        </div>
                      </div>
                    </div>
                </div>
              </div>
            <% end %>
    </div>

    <p class="float-right text-end">
      <a class="text-white font-weight-bold btn btn-outline-light rounded-pill" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="40" fill="currentColor" class="bi bi-caret-up" viewBox="0 0 16 16">
      <path d="M3.204 11h9.592L8 5.519 3.204 11zm-.753-.659 4.796-5.48a1 1 0 0 1 1.506 0l4.796 5.48c.566.647.106 1.659-.753 1.659H3.204a1 1 0 0 1-.753-1.659z"/>
    </svg></i></a>
    </p>
  </div>

  <footer class="footer text-center text-white text-muted rounded-top ">
    <div class="container p-4 pb-0 text-lg">

      <section class="mb-4">
      
        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1 rounded-pill" href="#!" target="_blank" role="button"><i class="fab fa-twitter"></i></a>
  
        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1 rounded-pill" href="#!" target="_blank" role="button"><i class="fab fa-instagram"></i></a>
  
        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1 rounded-pill" href="https://github.com/LaraPedroso" target="_blank" role="button"><i class="fab fa-github"></i></a>
      </section>
  <hr style= "color: white;">
    </div>
    <div class="text-center p-3 text-light"> © 2021 Lara Pedroso </div>
  </footer>
  </body>

app/views/home/post.html.erb
<div class="container mt-10 ">
    <div class="card fill mb-10 z-index-2 bg-gradient-light border-dark border-3">
        <div class="responsive-1 shadow-dark border-radius-xl page-header p-0 mt-n5 mx-4 z-index-10 bg-transparent img-fluid">
            <%= image_tag @post.image.variant(saver: { quality: 10 }, resize_to_fill: [1500, 400]) %>
        </div>
                <div class="card-body container text-dark py-1 px-3">
                    <div class="my-5" style="width: 95%; text-align: center;">
                        <h2 class="card-text text-dark my-3 fonts-L"><%= @post.name%></h2>
                    </div>
                    <div class="container">
                        <p class="card-text" style="font-size: 15px; fonts-L"><%= @post.content %>.</p>
                    </div>
                    </div>
                <div>
                    <table class="table border-radius-lg align-items-center mb-5">
                        <% if current_admin %>
                            <thead>
                            <%= form_with model: @comment, local: false, :html => {:id =>'comment-form' } do |form| %>
                                <tr>
                                    <th class="text-dark font-weight-bolder form-control">
                                        <%= form.text_area :content, maxlength: 255, class: "bg-light form-control p-2", placeholder: "Escreva seu Comentario...", required: true%>
                                        <%= form.submit 'Enviar', class: "text-white btn btn btn-outline-dark bg-gradient-dark font-weight-bold text-xs m-2" %>
                                        <%= form.hidden_field :post_id, :value => @post.id %>
                                    </th>
                                </tr>
                            <% end %>
                            </thead>
                        <% end %>
                    </table>
                    <% if admin_signed_in?%>
                        <%= render partial: 'rate', rating: @ratings %>
                    <% end %>
                    <div  id='comment-list' >
                        <%= render "comments", comments: @comments %>
                    </div>
                </div>  
            <div class="container">
                <%= link_to 'Voltar', root_path, class: "fonts-L btn btn-lg text-dark btn btn btn-outline-dark  L-black font-weight-bold mt-5 mb-4" %>
            </div>
        </div>
    </div>
</div>