config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }
  root to: 'home#index'
  resources :categories
  resources :roles
  resources :posts
  resources :comments
  resources :admins
  resources :ratings

  get '/post/:id', to: 'home#post', as: 'home_post'
  post '/create/admin', to: 'admins#create', as: 'admin_create'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <!-- Font Awesome Icons -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    
  </head>

<body class="g-sidenav-show corpo">
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-light bg-white" id="sidenav-main">
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto  max-height-vh-100" id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <li class="nav-item">
              <a class="nav-link text-dark " href="/">
                <span class="nav-link-text ms-1">Home</span>
              </a>
            </li>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <li class="nav-item">
            <a class="nav-link text-dark <%= controller_name == 'categories' ? 'active bg-gradient-dark' : '' %>  " href="/categories">
              <span class="nav-link-text ms-1">Categorias</span>
            </a>
          </li>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <li class="nav-item">
            <a class="nav-link text-dark <%= controller_name == 'roles' ? 'active bg-gradient-dark' : '' %>  " href="/roles">
              <span class="nav-link-text ms-1">Cargos</span>
            </a>
          </li>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <li class="nav-item">
            <a class="nav-link text-dark <%= controller_name == 'posts' ? 'active bg-gradient-dark' : '' %>  " href="/posts">
              <span class="nav-link-text ms-1">Posts</span>
            </a>
          </li>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <li class="nav-item">
            <a class="nav-link text-dark <%= controller_name == 'comments' ? 'active bg-gradient-dark' : '' %>  " href="/comments">
              <span class="nav-link-text ms-1">Comentarios</span>
            </a>
          </li>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <li class="nav-item">
            <a class="nav-link text-dark <%= controller_name == 'admins' ? 'active bg-gradient-dark' : '' %>  " href="/admins">
              <span class="nav-link-text ms-1">User</span>
            </a>
          </li>
        </div>
        <li class="nav-item container">
        <hr>
          <div class="text-dark d-md-flex">
            Logado: <strong><%= current_admin.email %></strong>.
          </div>
          <li class="nav-item container">
              <%= link_to 'Editar perfil', edit_admin_registration_path, :class => 'text-white btn btn btn-outline-dark bg-gradient-dark font-weight-bold text-xs m-2 navbar-link' %>
          </li>
            <li class="nav-item container">
              <%= link_to "Sair", destroy_admin_session_path, method: :delete, :class => 'text-dark btn btn btn-outline-dark text-xs m-2 navbar-link'  %>
          </li>
        </li>
      </ul>
    </div>
  </aside>
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
  <div class="container">
    <div class="nav-item d-xl-none ps-3 d-flex justify-content-end">
      <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
        <div class="sidenav-toggler-inner">
          <i class="fa fa-bars mt-5"></i>
        </div>
      </a>
    </div>
  </div>
    <div class="mt-5 container">
        <% if notice %>
          <p class="alert alert-success text-white"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger text-white"><%= alert %></p>
        <% end %>
    </div>
  <%= yield %>
  </main>
</body>
<script>

</script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloggg</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </head>

<body class="g-sidenav-show corpo">
<nav class="navbar navbar-expand-lg  ">
  <div class="container-fluid">
      <a class="navbar-brand">
          <% if admin_signed_in? %>
            <i class="fas fa-user  mx-3 text-light"></i><strong class="text-light"><%= current_admin.email %></strong>.
          <% end %>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon">
            <i class="fas fa-bars opacity-5"></i>
          </span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="ms-md-auto navbar-nav justify-content-end">
            <li class="nav-item d-flex align-items-center">
              <div class="d-flex flex-column bd-highlight mb-3">
                  <%= link_to 'Home', root_path, class: "text-white btn btn btn-outline-dark bg-gradient-dark font-weight-bold ms-4 bd-highlight" %>
                  <% if admin_signed_in? %>
                    <%= link_to 'Admin', categories_path, class: "text-dark btn btn btn-outline-dark ms-3" %>
                  <% end %>
                </div>
                    <div class="d-md-flex flex-column  mb-3"> 
                        <% if admin_signed_in? %>
                          <%= link_to 'Editar', edit_admin_registration_path, :class => 'text-white btn btn btn-outline-dark bg-gradient-dark font-weight-bold ms-1  p-2 bd-highlight' %> 
                          | <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'text-dark btn btn btn-outline-dark text-xs mx-2 navbar-link ms-2 p-2 bd-highlight'  %>
                        <% else %>
                          <%= link_to "Registrar-se", new_admin_registration_path, :class => 'text-white btn bg-gradient-dark font-weight-bold mt-3 p-2 bd-highlight'  %>
                          <%= link_to "Login", new_admin_session_path, :class => 'text-dark btn btn btn-outline-dark text-xs mx-2 navbar-link ms-2  bd-highlight'  %>
                        <% end %>
                  </div>
                  
                </div>
            </li>
          </ul>
        </div>
    </div>
</nav>

  <div class="container">
      <% if notice %>
        <p class="alert alert-success text-white"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger text-white"><%= alert %></p>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>